In [390]:
import pandas as pd
import numpy as np

In [391]:
df = pd.read_csv('../dataset/WA_Fn-UseC_-Telco-Customer-Churn.csv')
print(len(df))
df.head().T

7043


0             1               2  \
customerID              7590-VHVEG    5575-GNVDE      3668-QPYBK   
gender                      Female          Male            Male   
SeniorCitizen                    0             0               0   
Partner                        Yes            No              No   
Dependents                      No            No              No   
tenure                           1            34               2   
PhoneService                    No           Yes             Yes   
MultipleLines     No phone service            No              No   
InternetService                DSL           DSL             DSL   
OnlineSecurity                  No           Yes             Yes   
OnlineBackup                   Yes            No             Yes   
DeviceProtection                No           Yes              No   
TechSupport                     No            No              No   
StreamingTV                     No            No              No   
StreamingMovies                 No            No              No   
Contract            Month-to-month      One year  Month-to-month   
PaperlessBilling               Yes            No             Yes   
PaymentMethod     Electronic check  Mailed check    Mailed check   
MonthlyCharges               29.85         56.95           53.85   
TotalCharges                 29.85        1889.5          108.15   
Churn                           No            No             Yes   

                                          3                 4  
customerID                       7795-CFOCW        9237-HQITU  
gender                                 Male            Female  
SeniorCitizen                             0                 0  
Partner                                  No                No  
Dependents                               No                No  
tenure                                   45                 2  
PhoneService                             No               Yes  
MultipleLines              No phone service                No  
InternetService                         DSL       Fiber optic  
OnlineSecurity                          Yes                No  
OnlineBackup                             No                No  
DeviceProtection                        Yes                No  
TechSupport                             Yes                No  
StreamingTV                              No                No  
StreamingMovies                          No                No  
Contract                           One year    Month-to-month  
PaperlessBilling                         No               Yes  
PaymentMethod     Bank transfer (automatic)  Electronic check  
MonthlyCharges                         42.3              70.7  
TotalCharges                        1840.75            151.65  
Churn                                    No               Yes

In [392]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [393]:
#Pasos

total_charges = pd.to_numeric(df.TotalCharges, errors='coerce')
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')
df.TotalCharges = df.TotalCharges.fillna(0)
df[total_charges.isnull()][['customerID', 'TotalCharges']]

customerID  TotalCharges
488   4472-LVYGI           0.0
753   3115-CZMZD           0.0
936   5709-LVOEQ           0.0
1082  4367-NUYAO           0.0
1340  1371-DWPAZ           0.0
3331  7644-OMVMY           0.0
3826  3213-VVOLG           0.0
4380  2520-SGTTA           0.0
5218  2923-ARZLG           0.0
6670  4075-WKNIU           0.0
6754  2775-SEFEE           0.0

In [394]:
#Limpieza
replacer = lambda str: str.lower().str.replace(' ', '_').str.replace('-', '_')
df.columns = replacer(df.columns.str)
for col in list(df.dtypes[df.dtypes == 'object'].index):
    df[col] = replacer(df[col].str)
df.head().T


0             1               2  \
customerid              7590_vhveg    5575_gnvde      3668_qpybk   
gender                      female          male            male   
seniorcitizen                    0             0               0   
partner                        yes            no              no   
dependents                      no            no              no   
tenure                           1            34               2   
phoneservice                    no           yes             yes   
multiplelines     no_phone_service            no              no   
internetservice                dsl           dsl             dsl   
onlinesecurity                  no           yes             yes   
onlinebackup                   yes            no             yes   
deviceprotection                no           yes              no   
techsupport                     no            no              no   
streamingtv                     no            no              no   
streamingmovies                 no            no              no   
contract            month_to_month      one_year  month_to_month   
paperlessbilling               yes            no             yes   
paymentmethod     electronic_check  mailed_check    mailed_check   
monthlycharges               29.85         56.95           53.85   
totalcharges                 29.85        1889.5          108.15   
churn                           no            no             yes   

                                          3                 4  
customerid                       7795_cfocw        9237_hqitu  
gender                                 male            female  
seniorcitizen                             0                 0  
partner                                  no                no  
dependents                               no                no  
tenure                                   45                 2  
phoneservice                             no               yes  
multiplelines              no_phone_service                no  
internetservice                         dsl       fiber_optic  
onlinesecurity                          yes                no  
onlinebackup                             no                no  
deviceprotection                        yes                no  
techsupport                             yes                no  
streamingtv                              no                no  
streamingmovies                          no                no  
contract                           one_year    month_to_month  
paperlessbilling                         no               yes  
paymentmethod     bank_transfer_(automatic)  electronic_check  
monthlycharges                         42.3              70.7  
totalcharges                        1840.75            151.65  
churn                                    no               yes

In [395]:
df.churn = (df.churn == 'yes').astype(int)
df.churn.head()

0    0
1    0
2    1
3    0
4    1
Name: churn, dtype: int64

In [396]:
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
'phoneservice', 'multiplelines', 'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport', 'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling', 'paymentmethod']
numerical = ['tenure', 'monthlycharges', 'totalcharges']
df[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [397]:


# df['multiplelines']=df['multiplelines'].str.replace('no_phone_service','no')
# df['internetservice']=df['internetservice'].str.replace('dsl','yes').str.replace('fiber_optic','yes')
# df['onlinesecurity']=df['onlinesecurity'].str.replace('no_internet_service','no')
# df['onlinebackup']=df['onlinebackup'].str.replace('no_internet_service','no')
# df['deviceprotection']=df['deviceprotection'].str.replace('no_internet_service','no')
# df['techsupport']=df['techsupport'].str.replace('no_internet_service','no')
# df['streamingtv']=df['streamingtv'].str.replace('no_internet_service','no')
# df['streamingmovies']=df['streamingmovies'].str.replace('no_internet_service','no')


In [398]:
# df['contract'].unique()
df[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [399]:
del df['gender']
del df['phoneservice']
del df['multiplelines']
del df['streamingtv']
del df['deviceprotection']
# del df['streamingmovies']
# del df['onlinebackup']
# del df['seniorcitizen']
# del df['partner']
# del df['dependents']
# del df['techsupport']
# del df['paymentmethod']


# del df['tenure']
# del df['totalcharges']

In [400]:
df.head().T

0             1               2  \
customerid              7590_vhveg    5575_gnvde      3668_qpybk   
seniorcitizen                    0             0               0   
partner                        yes            no              no   
dependents                      no            no              no   
tenure                           1            34               2   
internetservice                dsl           dsl             dsl   
onlinesecurity                  no           yes             yes   
onlinebackup                   yes            no             yes   
techsupport                     no            no              no   
streamingmovies                 no            no              no   
contract            month_to_month      one_year  month_to_month   
paperlessbilling               yes            no             yes   
paymentmethod     electronic_check  mailed_check    mailed_check   
monthlycharges               29.85         56.95           53.85   
totalcharges                 29.85        1889.5          108.15   
churn                            0             0               1   

                                          3                 4  
customerid                       7795_cfocw        9237_hqitu  
seniorcitizen                             0                 0  
partner                                  no                no  
dependents                               no                no  
tenure                                   45                 2  
internetservice                         dsl       fiber_optic  
onlinesecurity                          yes                no  
onlinebackup                             no                no  
techsupport                             yes                no  
streamingmovies                          no                no  
contract                           one_year    month_to_month  
paperlessbilling                         no               yes  
paymentmethod     bank_transfer_(automatic)  electronic_check  
monthlycharges                         42.3              70.7  
totalcharges                        1840.75            151.65  
churn                                     0                 1

Comienza el procesado de la información. Para ello definimos objetivos y conjuntos de datos de entrenamiento y de validación.

In [401]:
from sklearn.model_selection import train_test_split
from random import randrange
# randrange(10000)
def dividirDatos(df, num):
    df_train_full, df_test = train_test_split(df, test_size=0.2, random_state=num)

    df_train, df_val = train_test_split(df_train_full, test_size=0.33, random_state=num)

    y_train = df_train.churn.values
    y_val = df_val.churn.values
    y_test=df_test.churn.values

    del df_test['churn']
    del df_train['churn']
    del df_val['churn']

    return(df_train_full, df_test,df_train, df_val, y_train, y_val, y_test)

Análisis de importancia de propiedades

In [402]:
df_train_full, df_test,df_train, df_val, y_train, y_val, y_test=dividirDatos(df, randrange(10000))
global_mean = df_train_full.churn.mean()
round(global_mean, 3)

0.27

In [403]:
# female_mean = df_train_full[df_train_full.gender == 'female'].churn.mean()
# print(round(female_mean, 3))
# male_mean = df_train_full[df_train_full.gender == 'male'].churn.mean()
# print(round(male_mean, 3))

In [404]:
# partner_yes = df_train_full[df_train_full.partner == 'yes'].churn.mean()
# print(round(partner_yes, 3))
# partner_no = df_train_full[df_train_full.partner == 'no'].churn.mean()
# print(round(partner_no, 3))

In [405]:
# from sklearn.metrics import mutual_info_score

# calculate_mi = lambda col: mutual_info_score(col, df_train_full.churn)

# df_mi = df_train_full[categorical].apply(calculate_mi)
# df_mi = df_mi.sort_values(ascending=False).to_frame(name='MI')
# df_mi

In [406]:
# print(df_train_full[numerical].corrwith(df_train_full.churn))

# print(round(df_train_full[df_train_full.tenure <= 2].churn.mean(), 3))
# print(round(df_train_full[(df_train_full.tenure > 3) & 
#                           (df_train_full.tenure <= 12)].churn.mean(), 3))
# print(round(df_train_full[df_train_full.tenure > 12].churn.mean(), 3))

# print(round(df_train_full[df_train_full.monthlycharges < 20].churn.mean(), 3))
# print(round(df_train_full[(df_train_full.monthlycharges > 21) & 
#                           (df_train_full.monthlycharges <= 50)].churn.mean(), 3))
# print(round(df_train_full[df_train_full.monthlycharges > 50].churn.mean(), 3))

Ingeniería de propiedades
Debemos adaptar las propiedades a nusetro sistema de entrenamiento. 
Para ello debemos hacer ciertas modificaciones. 
El objetivo será obtener la representación de los datos en forma de diccionario.

In [407]:
train_dict = df_train.to_dict(orient='records')
dict(sorted(train_dict[0].items()))

{'contract': 'month_to_month',
 'customerid': '4395_pzmsn',
 'dependents': 'no',
 'internetservice': 'fiber_optic',
 'monthlycharges': 85.55,
 'onlinebackup': 'yes',
 'onlinesecurity': 'no',
 'paperlessbilling': 'yes',
 'partner': 'no',
 'paymentmethod': 'electronic_check',
 'seniorcitizen': 1,
 'streamingmovies': 'yes',
 'techsupport': 'no',
 'tenure': 5,
 'totalcharges': 408.5}

In [408]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)
dv.fit(train_dict)

DictVectorizer(sparse=False)

In [409]:
X_train = dv.transform(train_dict)
X_train[0]

array([  1. ,   0. ,   0. , ...,   0. ,   5. , 408.5])

In [410]:
dv.get_feature_names_out()

array(['contract=month_to_month', 'contract=one_year',
       'contract=two_year', ..., 'techsupport=yes', 'tenure',
       'totalcharges'], dtype=object)

Entrenamiento del modelo

In [411]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='liblinear')
# model = LogisticRegression(solver='newton-cholesky')
model.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [412]:
val_dict = df_val.to_dict(orient='records')
X_val = dv.transform(val_dict)
y_pred = model.predict_proba(X_val)
y_pred

array([[0.98354296, 0.01645704],
       [0.78620482, 0.21379518],
       [0.78164269, 0.21835731],
       ...,
       [0.34663818, 0.65336182],
       [0.80683208, 0.19316792],
       [0.87228345, 0.12771655]])

In [413]:
y_pred = model.predict_proba(X_val)[:, 1]
y_pred

array([0.01645704, 0.21379518, 0.21835731, ..., 0.65336182, 0.19316792,
       0.12771655])

In [414]:
churn = y_pred >= 0.5
churn

array([False, False, False, ...,  True, False, False])

In [415]:
round((y_val == churn).mean(), 3) 

0.806

In [416]:


test_dict = df_test.to_dict(orient='records')
X_test = dv.transform(test_dict)
y_pred_test = model.predict_proba(X_test)

y_pred_test = model.predict_proba(X_test)[:, 1]

churn = y_pred_test >= 0.5

round((y_test == churn).mean(), 3)  

0.813

In [417]:
resultadosVal=[]
resultadosTest=[]
for i in range(1000):
    # dividir datos
    df_train_full, df_test,df_train, df_val, y_train, y_val, y_test=dividirDatos(df, randrange(1000))
    # randrange(10000)
    # entrenar
    # model = LogisticRegression(solver='liblinear')
    # model.fit(X_train, y_train)

    # validacion del entrenamiento
    val_dict = df_val.to_dict(orient='records')
    X_val = dv.transform(val_dict)
    y_pred = model.predict_proba(X_val)
    y_pred = model.predict_proba(X_val)[:, 1]
    churn = y_pred >= 0.5
    resultadosVal.append(round((y_val == churn).mean(), 3))

    # test
    test_dict = df_test.to_dict(orient='records')
    X_test = dv.transform(test_dict)
    y_pred_test = model.predict_proba(X_test)

    y_pred_test = model.predict_proba(X_test)[:, 1]

    churn = y_pred_test >= 0.5

    resultadosTest.append(round((y_test == churn).mean(), 3) )

mediaVal= np.median(resultadosVal)
mediaTest=np.median(resultadosTest)

print(mediaVal)
print(mediaTest)

0.805
0.804


In [418]:
print(resultadosVal, len(resultadosVal))

[0.805, 0.805, 0.812, 0.798, 0.795, 0.811, 0.794, 0.806, 0.81, 0.823, 0.805, 0.805, 0.803, 0.798, 0.809, 0.813, 0.819, 0.802, 0.818, 0.801, 0.809, 0.815, 0.801, 0.815, 0.797, 0.803, 0.808, 0.799, 0.81, 0.81, 0.791, 0.805, 0.815, 0.799, 0.802, 0.807, 0.814, 0.813, 0.805, 0.793, 0.795, 0.804, 0.819, 0.808, 0.799, 0.796, 0.802, 0.792, 0.817, 0.819, 0.811, 0.807, 0.805, 0.811, 0.804, 0.803, 0.807, 0.814, 0.812, 0.811, 0.791, 0.817, 0.804, 0.795, 0.795, 0.815, 0.804, 0.804, 0.787, 0.81, 0.804, 0.809, 0.816, 0.799, 0.797, 0.823, 0.808, 0.795, 0.809, 0.812, 0.801, 0.806, 0.806, 0.814, 0.809, 0.793, 0.803, 0.812, 0.797, 0.802, 0.79, 0.794, 0.803, 0.805, 0.807, 0.815, 0.803, 0.81, 0.799, 0.803, 0.794, 0.808, 0.79, 0.802, 0.803, 0.79, 0.802, 0.804, 0.803, 0.806, 0.809, 0.812, 0.809, 0.815, 0.797, 0.808, 0.826, 0.799, 0.816, 0.819, 0.806, 0.812, 0.801, 0.818, 0.819, 0.801, 0.803, 0.808, 0.806, 0.808, 0.809, 0.798, 0.798, 0.821, 0.822, 0.808, 0.804, 0.795, 0.811, 0.811, 0.797, 0.806, 0.82, 0.816, 

In [419]:
print(resultadosTest)

[0.797, 0.808, 0.803, 0.801, 0.793, 0.805, 0.82, 0.801, 0.801, 0.781, 0.784, 0.807, 0.823, 0.817, 0.801, 0.813, 0.789, 0.811, 0.807, 0.808, 0.787, 0.801, 0.807, 0.806, 0.806, 0.817, 0.791, 0.801, 0.798, 0.802, 0.809, 0.802, 0.788, 0.799, 0.809, 0.796, 0.815, 0.796, 0.793, 0.813, 0.811, 0.792, 0.788, 0.811, 0.811, 0.812, 0.809, 0.812, 0.801, 0.773, 0.788, 0.803, 0.803, 0.808, 0.785, 0.801, 0.805, 0.815, 0.806, 0.806, 0.806, 0.823, 0.806, 0.811, 0.811, 0.806, 0.809, 0.808, 0.813, 0.808, 0.813, 0.811, 0.796, 0.802, 0.811, 0.813, 0.811, 0.811, 0.801, 0.789, 0.807, 0.806, 0.816, 0.799, 0.796, 0.815, 0.808, 0.816, 0.789, 0.806, 0.82, 0.817, 0.813, 0.815, 0.796, 0.805, 0.801, 0.794, 0.815, 0.827, 0.794, 0.82, 0.82, 0.816, 0.803, 0.791, 0.806, 0.801, 0.803, 0.824, 0.801, 0.813, 0.8, 0.795, 0.796, 0.793, 0.787, 0.799, 0.804, 0.806, 0.801, 0.801, 0.823, 0.781, 0.773, 0.801, 0.816, 0.816, 0.803, 0.8, 0.799, 0.79, 0.8, 0.791, 0.799, 0.805, 0.822, 0.818, 0.797, 0.809, 0.809, 0.8, 0.813, 0.796, 0.79